### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by joshp23** [joshp23/YOURLS-Compliance#10]
This list may or may not ever get done

- [ ] Add option to use the YOURLS default style for the intercept page (no template) and make that default
- [x] Add integration with [Snapshot Preview](https://github.com/joshp23/YOURLS-Snapshot) via U-SRV to optionally show a snapshot of flagged links on intercept
- [ ] add option to un-flag in admin interface
- [ ] add "go to flag-list" option in admin interface
